### ISSUE TITLE
About the reason of having cluster nodes 

### ISSUE THREAD

**Issue by hafezmg48** [evilsocket/cake#10]
Thanks for your valuable contribution.
I have the following question that I need some clarification. It would probably be also noteworthy to be mentioned in the README description for more clarity.
From my basic understanding, in cake we are splitting the model into its layers and distributing those layers to separate nodes because a huge 70B model will not fit into a single normal GPU. So my question is that what would be the benefit of having a cluster of these nodes on our network instead of having only a single worker and just loading and offloading each layer of model one by one? Because my understanding is that the model inference is sequential, so one node has to wait for the process of previous layers to finish to start its process. So basically having multiple nodes would appear redundant. Unless, we have some sort of pipelining mechanism that would feed batches to the nodes one at a time to perform pipelining. Is that our intention here? Could you please provide some guidance and explanation on this? Thanks again.

**Comment by SEVENID** [comment]
* If you have more than one request to process. 
* If you have many weak devices.
* If none of the end devices has enough memory to even store the entire model in RAM.  
* Just for distributed fun.

**Comment by evilsocket** [comment]
As per README:

The goal of the project is being able to run big (70B+) models by repurposing consumer hardware into an heterogeneous cluster of iOS, Android, macOS, Linux and Windows devices, effectively leveraging [planned obsolescence](https://en.wikipedia.org/wiki/Planned_obsolescence) as a tool to make AI more accessible and democratic.

I would also like to add: coding is fun, sometimes you do things just to see if they can be done.

**Comment by hafezmg48** [comment]
> * If you have more than one request to process.
> * If you have many weak devices.
> * If none of the end devices has enough memory to even store the entire model in RAM.
> * Just for distributed fun.

In addition to this, I believe that there is a profound practical use for this project's cluster system. If we assume a batch of multiple inferences, the sequential model layer executions in cluster nodes can pipeline multiple batches (ex. Node 3 processing layer 3 of batch 1, meanwhile Node 2 and Node 1 also process layer 2 of batch 2 and layer 1 of batch 3). This highly increases the total token/sec rate. Unfortunately I do not have enough coding expertise to evaluate this, but I think it can be an interesting feature.

**Comment by evilsocket** [comment]
yes it will be interesting to see how node reuse over batching can increase performances ... there's an attention layer with kv-cache already so in a way information get cached, but that would push things further if i understand correctly ... definitely food for thought! thank you @hafezmg48 :D It would be interesting to keep this conversation going on this Discord server if you want https://discord.com/invite/btZpkp45gQ
