### ISSUE TITLE
Error in model.forward: error in forward batch operation for block

### ISSUE THREAD

**Issue by hash-momo** [evilsocket/cake#13]
The first time I call the API, it works fine. However, when I call the REST API for the second time, the master node reports the error:
`cake/api/mod.rs:98:10: called Result::unwrap() on an Err value: error in model.forward: error in forward batch operation for block 29: error receiving response for Batch`
Additionally, one of my workers will also trigger an error and then stop:
`src/cake/worker.rs:225:26: called Result::unwrap() on an Err value: cannot broadcast [28, 28] to [1, 32, 28, 65]`

**Comment by caohuilong** [comment]
The problem still exists and has not been solved. 
When sending the second request, the master reports an error
![image](https://github.com/user-attachments/assets/0defc7cd-f898-4597-9c45-0b7555ceaab2)

one of the worker reports 
![image](https://github.com/user-attachments/assets/4ef6f50d-4ba7-42a5-8c45-6bee3d0fb459)

**Comment by evilsocket** [comment]
@caohuilong are you sure you pulled the fix before compiling?

**Comment by caohuilong** [comment]
> @caohuilong are you sure you pulled the fix before compiling?

yes, i pull the repo today and have check the code is the newest.

**Comment by angive** [comment]
I hope the author can resolve this issue as soon as possible.

**Comment by evilsocket** [comment]
the author works at this project for fun during his free time

**Comment by evilsocket** [comment]
closed with https://github.com/evilsocket/cake/pull/32
