### ISSUE TITLE
Is it possible to use quantized models?

### ISSUE THREAD

**Issue by ManuXD32** [evilsocket/cake#22]
Firs of all, I wanna thank you for your hard work, I love this project and I thinks it's awesome to be able to handle inference on different devices.
 As for me, the point in splitting a model among different devices, lays in my current RAM limitations, so I guess it would have much more sense to be able to use quantized versions of the big models.

**Comment by evilsocket** [comment]
yes

**Comment by evilsocket** [comment]
You are using a GGUF file, which is not supported by Cake. Only safetensors.

**Comment by ManuXD32** [comment]
> You are using a GGUF file, which is not supported by Cake. Only safetensors.

Are there plans to support gguf format?

**Comment by evilsocket** [comment]
possibly at some point, i work on this on my free time so i won't commit to a specific timeline

**Comment by ManuXD32** [comment]
> possibly at some point, i work on this on my free time so i won't commit to a specific timeline

Okay!! Thanks for your effort.
