### ISSUE TITLE
无法编译成功

### ISSUE THREAD

**Issue by wwdhf** [evilsocket/cake#6]
C:\Users\Administrator\Desktop\cake>cargo build --release
warning: C:\Users\Administrator\Desktop\cake\cake-ios\Cargo.toml: `crate_type` is deprecated in favor of `crate-type` and will not work in the 2024 edition
(in the `cake` library target)
   Compiling cudarc v0.11.7
   Compiling candle-kernels v0.6.0
   Compiling clap_lex v0.7.1
   Compiling bit-vec v0.6.3
   Compiling strsim v0.11.1
   Compiling nom v7.1.3
   Compiling console v0.15.8
   Compiling esaxx-rs v0.1.10
error: failed to run custom build command for `cudarc v0.11.7`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Desktop\cake\target\release\build\cudarc-95f6bdd5c33de08a\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cudarc-0.11.7\build.rs:82:14:
  Unsupported cuda toolkit version: `11.0`. Please raise a github issue.
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
     3: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `candle-kernels v0.6.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Desktop\cake\target\release\build\candle-kernels-644872f2b8f06ed1\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/compatibility.cuh
  cargo:rerun-if-changed=src/cuda_utils.cuh
  cargo:rerun-if-changed=src/binary_op_macros.cuh
  cargo:info=["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]
  cargo:rerun-if-env-changed=CUDA_COMPUTE_CAP

  --- stderr
  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen_cuda-0.1.5\src\lib.rs:492:9:
  assertion `left == right` failed
    left: "Field \"compute_cap\" is not a valid field to query."
   right: "compute_cap"
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: core::panicking::assert_failed_inner
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:409
     3: core::panicking::assert_failed
     4: bindgen_cuda::cuda_include_dir::{{closure}}
     5: <bindgen_cuda::Builder as core::default::Default>::default
     6: std::rt::lang_start
     7: std::rt::lang_start
     8: __ImageBase
     9: std::rt::lang_start
    10: std::rt::lang_start_internal
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\rt.rs:141
    11: std::rt::lang_start
    12: main
    13: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    14: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    15: BaseThreadInitThunk
    16: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

C:\Users\Administrator\Desktop\cake>nvidia-smi
Tue Jul 16 01:15:46 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 457.30       Driver Version: 457.30       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108... WDDM  | 00000000:01:00.0  On |                  N/A |
|100%   29C    P8    16W / 250W |    555MiB / 11264MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1340    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A     12420    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     12928    C+G   ...m Files\ToDesk\ToDesk.exe    N/A      |
|    0   N/A  N/A     13352    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     13940    C+G   ...d\runtime\WeChatAppEx.exe    N/A      |
|    0   N/A  N/A     14476    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     15492    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     17964    C+G   ...ray\lghub_system_tray.exe    N/A      |
|    0   N/A  N/A     18256    C+G   ...e\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A     18744    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     19444    C+G   ...lPanel\SystemSettings.exe    N/A      |
+-----------------------------------------------------------------------------+

C:\Users\Administrator\Desktop\cake>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:48_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28540450_0

**Comment by evilsocket** [comment]
CUDA >= 12.2 is required, you seem to be using version 11 which is very old (in fact I see 2020 there) https://github.com/evilsocket/cake/issues/3
