### ISSUE TITLE
Inquiries about the possibility of supporting windows systems

### ISSUE THREAD

**Issue by longxiaocao** [evilsocket/cake#7]
Hello developers, I see you this project, really awesome, I have been struggling with the lack of performance of the device, and do not have much money to buy A100 graphics card, because to buy milk powder for the child, haha, would like to consult whether there is the intention to join the windows system, I see that the mac, linux, android have support, we are mainly on the side of windows 7! I see mac, linux, and android are all supported, we are mainly windows 7 on our side, we have six computers, it would be nice to have a cluster that supports windows.

**Comment by evilsocket** [comment]
In theory Cake already supports Windows + CUDA and can be built for it, but I never tried so I didn't add it to the supported systems table.

**Comment by longxiaocao** [comment]
Awesome, I hope you can test it and also if you can try it in separate cpu or cuda form, after all, office computers don't have very strong graphics cards ;-)

**Comment by evilsocket** [comment]
If you check the README it's already explained how to build with or without CUDA, that should work on every platform :D
