### ISSUE TITLE
bug with tokenizer and gibberish output

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/cake#9]
the tokenizer has issues resolving a few tokens including special ones (they will be shown in the output as <token N>), which is causing all sorts of gibberish output ... it's probably a matter of parsing the model/tokenizer.json properly

**Comment by evilsocket** [comment]
the model responds well when prompt template is not used (https://github.com/evilsocket/cake/blob/main/cake-core/src/models/llama3/llama.rs#L266)

**Comment by caohuilong** [comment]
Has this been fixed? I met the same problem.

**Comment by evilsocket** [comment]
@caohuilong the issue is open, the bug has not been fixed, waiting for the candle team to respond

**Comment by evilsocket** [comment]
https://github.com/evilsocket/cake/pull/32
